services:
  panel:
    build:
      context: .
      args:
        GITHUB_NPM_AUTH_TOKEN: "${GITHUB_NPM_AUTH_TOKEN}"
        FONTAWESOME_NPM_AUTH_TOKEN: "${FONTAWESOME_NPM_AUTH_TOKEN}"
        VITE_UPLOAD_API_URL: "${VITE_UPLOAD_API_URL}"
        VITE_MAPBOX_ACCESS_TOKEN: "${VITE_MAPBOX_ACCESS_TOKEN}"
        VITE_GOOGLE_MAPS_API_KEY: '${VITE_GOOGLE_MAPS_API_KEY}'
        VITE_GOOGLE_PLACE_API_KEY: '${VITE_GOOGLE_PLACE_API_KEY}'
        VITE_HASURA_WSS: "${VITE_HASURA_WSS}"
        VITE_HASURA_HTTPS: "${VITE_HASURA_HTTPS}"
        VITE_BI_API_URL: '${VITE_BI_API_URL}'
        VITE_API_URL: '${VITE_API_URL}'
    networks:
      - shared_network_to_caddy
    restart: always
    #ports:
    #  - "80:80"

networks:
  shared_network_to_caddy:
    name: shared_network_to_caddy
    external: true
